# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ray/codes/702code_1007/stereo_vision_grasp/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from lib.modified_item import ClickableImage

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1800, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        #self.left_img = QtWidgets.QLabel(self.centralwidget)
        self.left_img = ClickableImage(self.centralwidget)
        self.left_img.setGeometry(QtCore.QRect(20, 10, 640, 480))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.left_img.setFont(font)
        self.left_img.setObjectName("left_img")
        self.pushButton_open_cam = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open_cam.setGeometry(QtCore.QRect(1320, 270, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_open_cam.setFont(font)
        self.pushButton_open_cam.setObjectName("pushButton_open_cam")
        self.right_img = QtWidgets.QLabel(self.centralwidget)
        self.right_img.setGeometry(QtCore.QRect(670, 10, 640, 480))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.right_img.setFont(font)
        self.right_img.setObjectName("right_img")
        self.depth_img = QtWidgets.QLabel(self.centralwidget)
        self.depth_img.setGeometry(QtCore.QRect(20, 490, 640, 480))
        self.depth_img.setObjectName("depth_img")
        self.label_left = QtWidgets.QLabel(self.centralwidget)
        self.label_left.setGeometry(QtCore.QRect(20, 450, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_left.setFont(font)
        self.label_left.setTextFormat(QtCore.Qt.PlainText)
        self.label_left.setScaledContents(True)
        self.label_left.setIndent(-1)
        self.label_left.setObjectName("label_left")
        self.label_right = QtWidgets.QLabel(self.centralwidget)
        self.label_right.setGeometry(QtCore.QRect(1210, 450, 91, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_right.setFont(font)
        self.label_right.setTextFormat(QtCore.Qt.PlainText)
        self.label_right.setScaledContents(True)
        self.label_right.setIndent(-1)
        self.label_right.setObjectName("label_right")
        self.label_depth = QtWidgets.QLabel(self.centralwidget)
        self.label_depth.setGeometry(QtCore.QRect(20, 920, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_depth.setFont(font)
        self.label_depth.setTextFormat(QtCore.Qt.PlainText)
        self.label_depth.setScaledContents(True)
        self.label_depth.setIndent(-1)
        self.label_depth.setObjectName("label_depth")
        self.pushButton_get_depth = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_get_depth.setGeometry(QtCore.QRect(1480, 270, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_get_depth.setFont(font)
        self.pushButton_get_depth.setObjectName("pushButton_get_depth")
        self.pushButton_calib = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calib.setGeometry(QtCore.QRect(1640, 320, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_calib.setFont(font)
        self.pushButton_calib.setObjectName("pushButton_calib")
        self.label_class = QtWidgets.QLabel(self.centralwidget)
        self.label_class.setGeometry(QtCore.QRect(1320, 570, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_class.setFont(font)
        self.label_class.setObjectName("label_class")
        self.label_obj_cur_pose = QtWidgets.QLabel(self.centralwidget)
        self.label_obj_cur_pose.setGeometry(QtCore.QRect(1320, 620, 681, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_obj_cur_pose.setFont(font)
        self.label_obj_cur_pose.setObjectName("label_obj_cur_pose")
        self.pushButton_enable_detection = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_enable_detection.setGeometry(QtCore.QRect(1640, 270, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_enable_detection.setFont(font)
        self.pushButton_enable_detection.setObjectName("pushButton_enable_detection")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(1320, 0, 261, 251))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.pushButton_forward = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_forward.setGeometry(QtCore.QRect(50, 50, 40, 40))
        self.pushButton_forward.setStyleSheet("QPushButton {\n"
"    border-image: url(icons/up1.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(icons/up2.png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(icons/up3.png);\n"
"}")
        self.pushButton_forward.setText("")
        self.pushButton_forward.setObjectName("pushButton_forward")
        self.pushButton_down = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_down.setGeometry(QtCore.QRect(50, 200, 40, 40))
        self.pushButton_down.setStyleSheet("QPushButton {\n"
"    border-image: url(icons/down1.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(icons/down2.png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(icons/down3.png);\n"
"}")
        self.pushButton_down.setText("")
        self.pushButton_down.setObjectName("pushButton_down")
        self.pushButton_backward = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_backward.setGeometry(QtCore.QRect(50, 100, 40, 40))
        self.pushButton_backward.setStyleSheet("QPushButton {\n"
"    border-image: url(icons/down1.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(icons/down2.png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(icons/down3.png);\n"
"}")
        self.pushButton_backward.setText("")
        self.pushButton_backward.setObjectName("pushButton_backward")
        self.pushButton_left = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_left.setGeometry(QtCore.QRect(10, 170, 40, 40))
        self.pushButton_left.setStyleSheet("QPushButton {\n"
"    border-image: url(icons/left1.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(icons/left2.png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(icons/left3.png);\n"
"}")
        self.pushButton_left.setText("")
        self.pushButton_left.setObjectName("pushButton_left")
        self.pushButton_right = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_right.setGeometry(QtCore.QRect(90, 170, 40, 40))
        self.pushButton_right.setStyleSheet("QPushButton {\n"
"    border-image: url(icons/right1.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(icons/right2.png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(icons/right3.png);\n"
"}")
        self.pushButton_right.setText("")
        self.pushButton_right.setObjectName("pushButton_right")
        self.pushButton_up = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_up.setGeometry(QtCore.QRect(50, 150, 40, 40))
        self.pushButton_up.setStyleSheet("QPushButton {\n"
"    border-image: url(icons/up1.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(icons/up2.png);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-image: url(icons/up3.png);\n"
"}")
        self.pushButton_up.setText("")
        self.pushButton_up.setObjectName("pushButton_up")
        self.pushButton_led_up = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_led_up.setGeometry(QtCore.QRect(130, 50, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_led_up.setFont(font)
        self.pushButton_led_up.setObjectName("pushButton_led_up")
        self.pushButton_led_down = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_led_down.setGeometry(QtCore.QRect(130, 100, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_led_down.setFont(font)
        self.pushButton_led_down.setObjectName("pushButton_led_down")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(150, 170, 86, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(1590, 30, 191, 211))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1580, 0, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_VCap_left = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_VCap_left.setGeometry(QtCore.QRect(1320, 320, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_VCap_left.setFont(font)
        self.pushButton_VCap_left.setObjectName("pushButton_VCap_left")
        self.pushButton_tracking = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_tracking.setGeometry(QtCore.QRect(1480, 320, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_tracking.setFont(font)
        self.pushButton_tracking.setObjectName("pushButton_tracking")
        self.pushButton_grasp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_grasp.setGeometry(QtCore.QRect(1320, 470, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_grasp.setFont(font)
        self.pushButton_grasp.setObjectName("pushButton_grasp")
        self.lineEditx = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditx.setGeometry(QtCore.QRect(1330, 380, 113, 25))
        self.lineEditx.setObjectName("lineEditx")
        self.lineEdity = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdity.setGeometry(QtCore.QRect(1490, 380, 113, 25))
        self.lineEdity.setObjectName("lineEdity")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(1630, 380, 113, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_move = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_move.setGeometry(QtCore.QRect(1640, 410, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_move.setFont(font)
        self.pushButton_move.setObjectName("pushButton_move")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1320, 380, 21, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1470, 380, 21, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1620, 380, 21, 17))
        self.label_4.setObjectName("label_4")
        self.pushButton_move_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_move_2.setGeometry(QtCore.QRect(1480, 470, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_move_2.setFont(font)
        self.pushButton_move_2.setObjectName("pushButton_move_2")
        self.right_img_2 = QtWidgets.QLabel(self.centralwidget)
        self.right_img_2.setGeometry(QtCore.QRect(670, 500, 640, 480))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.right_img_2.setFont(font)
        self.right_img_2.setObjectName("right_img_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.left_img.setText(_translate("MainWindow", "wait for left image!"))
        self.pushButton_open_cam.setText(_translate("MainWindow", "打开摄像头"))
        self.right_img.setText(_translate("MainWindow", "wait for right image!"))
        self.depth_img.setText(_translate("MainWindow", "TextLabel"))
        self.label_left.setText(_translate("MainWindow", "左视图"))
        self.label_right.setText(_translate("MainWindow", "右视图"))
        self.label_depth.setText(_translate("MainWindow", "深度图"))
        self.pushButton_get_depth.setText(_translate("MainWindow", "获取深度图"))
        self.pushButton_calib.setText(_translate("MainWindow", "获取标定图像"))
        self.label_class.setText(_translate("MainWindow", "目标类别："))
        self.label_obj_cur_pose.setText(_translate("MainWindow", "当前目标位置："))
        self.pushButton_enable_detection.setText(_translate("MainWindow", "开始目标检测"))
        self.groupBox.setTitle(_translate("MainWindow", "控制区"))
        self.pushButton_led_up.setText(_translate("MainWindow", "led_up"))
        self.pushButton_led_down.setText(_translate("MainWindow", "led_down"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.label.setText(_translate("MainWindow", "状态日志"))
        self.pushButton_VCap_left.setText(_translate("MainWindow", "开始录制"))
        self.pushButton_tracking.setText(_translate("MainWindow", "tracking"))
        self.pushButton_grasp.setText(_translate("MainWindow", "grasp"))
        self.pushButton_move.setText(_translate("MainWindow", "move"))
        self.label_2.setText(_translate("MainWindow", "x:"))
        self.label_3.setText(_translate("MainWindow", "y:"))
        self.label_4.setText(_translate("MainWindow", "z:"))
        self.pushButton_move_2.setText(_translate("MainWindow", "back"))
        self.right_img_2.setText(_translate("MainWindow", "wait for sonar image!"))
